#ifndef FROKCOMMONDEFAULTS_H
#define FROKCOMMONDEFAULTS_H

#define FROK_LIB_COMMON_DEFAULT_CONFIG_FILENAME     "/etc/frok/frok.conf"
#define FROK_LIB_COMMON_DEFAULT_OUTPUT_FILENAME     "/var/log/frok.log"
#define FROK_DEFAULT_PHOTO_BASE_PATH                "/home/zda/faces"
#define FROK_DEFAULT_TARGET_PHOTOS_PATH             "/home/zda/faces"


#define FROK_PARAM_OUTPUT_FILENAME      "OUTPUT_FILE"
#define FROK_PARAM_PHOTO_BASE_PATH      "PHOTO_BASE_PATH"
#define FROK_PARAM_TARGET_PHOTOS_PATH   "TARGET_PHOTOS_PATH"

#endif // FROKCOMMONDEFAULTS_H
