#ifndef FROKCOMMONDEFAULTS_H
#define FROKCOMMONDEFAULTS_H

#define FROK_LIB_COMMON_DEFAULT_CONFIG_FILENAME "/etc/frok/frok.conf"
#define FROK_LIB_COMMON_DEFAULT_OUTPUT_FILENAME "/var/log/frok.log"

#endif // FROKCOMMONDEFAULTS_H
